// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8gqh_NMv3dyKla8GAi8KUdkzAoAt-vQ',
    appId: '1:889787544189:web:62a27e3415f05412f2f714',
    messagingSenderId: '889787544189',
    projectId: 'muzic-2b00e',
    authDomain: 'muzic-2b00e.firebaseapp.com',
    storageBucket: 'muzic-2b00e.firebasestorage.app',
    measurementId: 'G-5DG5L6KKX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6QFF7JGHBym21RBMA5p9_O2njq2Xtbmc',
    appId: '1:889787544189:android:b4c93e3f3a87cc7df2f714',
    messagingSenderId: '889787544189',
    projectId: 'muzic-2b00e',
    storageBucket: 'muzic-2b00e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHTNkeye4Krl0k8R-CA5KUVgoAeJ5uFY',
    appId: '1:889787544189:ios:4fea057734ae4deff2f714',
    messagingSenderId: '889787544189',
    projectId: 'muzic-2b00e',
    storageBucket: 'muzic-2b00e.firebasestorage.app',
    iosBundleId: 'com.example.muzik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHTNkeye4Krl0k8R-CA5KUVgoAeJ5uFY',
    appId: '1:889787544189:ios:4fea057734ae4deff2f714',
    messagingSenderId: '889787544189',
    projectId: 'muzic-2b00e',
    storageBucket: 'muzic-2b00e.firebasestorage.app',
    iosBundleId: 'com.example.muzik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH8gqh_NMv3dyKla8GAi8KUdkzAoAt-vQ',
    appId: '1:889787544189:web:74ca6efff8501777f2f714',
    messagingSenderId: '889787544189',
    projectId: 'muzic-2b00e',
    authDomain: 'muzic-2b00e.firebaseapp.com',
    storageBucket: 'muzic-2b00e.firebasestorage.app',
    measurementId: 'G-N4K0DSB5W1',
  );
}
